# Generated by Django 3.1.2 on 2020-12-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201205_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
