# Generated by Django 3.1.2 on 2020-12-07 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_paymentinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='CVV',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='card_number',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='ProductPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_pic')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
